package org.itmo;

import java.util.*;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.stream.Collectors;

class Graph {
    private final Integer CORES = Runtime.getRuntime().availableProcessors() * 2;
    private final int V;
    private final ArrayList<Integer>[] adjList;
    private final ExecutorService executor;

    Graph(int vertices) {
        this.V = vertices;
        adjList = new ArrayList[vertices];
        for (int i = 0; i < vertices; ++i) {
            adjList[i] = new ArrayList<>();
        }

        executor = Executors.newFixedThreadPool(CORES);
    }

    void addEdge(int src, int dest) {
        if (!adjList[src].contains(dest)) {
            adjList[src].add(dest);
        }
    }

    void parallelBFS(int startVertex) {
        AtomicBoolean[] visited = new AtomicBoolean[V];
        for (Integer i = 0; i < V; i++) {
            visited[i] = new AtomicBoolean(false);
        }
        visited[startVertex].set(true);

        ConcurrentQueueBalancer balancer = new ConcurrentQueueBalancer(CORES);
        balancer.add(startVertex);

        while (true) {
            ConcurrentQueueBalancer nextBalancer = new ConcurrentQueueBalancer(CORES);

            List<Future<?>> futures = balancer.getQueues().stream()
                    .filter((queue) -> !queue.isEmpty())
                    .map((queue) -> executor.submit(() -> {
                        while (!queue.isEmpty()) {
                            Integer vertex = queue.poll();

                            for (int n : adjList[vertex]) {
                                Boolean isVisited = visited[n].getAndSet(true);
                                if (!isVisited) {
                                    nextBalancer.add(n);
                                }
                            }
                        }
                    })).collect(Collectors.toList());

            if (futures.isEmpty()) {
                break;
            }

            for (Future<?> f : futures) {
                try {
                    f.get();
                } catch (InterruptedException | ExecutionException e) {
                    e.printStackTrace();
                }
            }

            balancer = nextBalancer;
        }
    }

    // Generated by ChatGPT
    void bfs(int startVertex) {
        boolean[] visited = new boolean[V];

        LinkedList<Integer> queue = new LinkedList<>();

        visited[startVertex] = true;
        queue.add(startVertex);

        while (!queue.isEmpty()) {
            startVertex = queue.poll();

            for (int n : adjList[startVertex]) {
                if (!visited[n]) {
                    visited[n] = true;
                    queue.add(n);
                }
            }
        }
    }

}
